### ISSUE TITLE
Homework 1

### ISSUE THREAD

**Issue by pistriak** [Bezverhyi/PhoneNumber#1]
1. Exclude IDE-generated files from the repository; Use .gitignore for it. 
2. Read "Code Conventions for the Java Programming Language" goo.gl/b0XugS﻿ and format you code accordingly;
3. Don't leave meaningless comments in your code.

**Comment by Bezverhyi** [comment]
1. Exclude IDE-generated files from the repository.
2. I read Convention and if I understood correctly changed in accordance with the Convention. There are moments in which I have a question, ask tomorrow.
